"""user_id on annotation and edit

Revision ID: f41ac7f968b5
Revises: eb6498f2b3e3
Create Date: 2021-06-05 19:27:57.773783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41ac7f968b5'
down_revision = 'eb6498f2b3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'annotation', 'user', ['user_id'], ['id'])
    op.drop_column('annotation', 'author')
    op.add_column('edit', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'edit', 'user', ['user_id'], ['id'])
    op.drop_column('edit', 'editor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edit', sa.Column('editor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'edit', type_='foreignkey')
    op.drop_column('edit', 'user_id')
    op.add_column('annotation', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'annotation', type_='foreignkey')
    op.drop_column('annotation', 'user_id')
    # ### end Alembic commands ###
